### ISSUE TITLE
Automatic deploy from tagged version to CDN

### ISSUE THREAD

**Issue by ghost** [xivapi/vue-xivtooltips#2]
Probably just need some more circleci stuff.

**Comment by ayyaruq** [comment]
Prob best bet here with CircleCI is to have it watch tags to create a release, then point `https://cdn.jsdelivr.net/gh/nonowazu/vue-xivtooltips@TAG/dist/vue-xivtooltips.min.{js,css}` and it should work by magic provided the dist folder is uploaded properly in the release.

**Comment by ghost** [comment]
Ay solved with PR #23
