### ISSUE TITLE
MP not displayed

### ISSUE THREAD

**Issue by ArcaneDisgea** [xivapi/vue-xivtooltips#27]
BLU Mage spells do not seem to display MP appropriately.

Tooltip: 
![image](https://user-images.githubusercontent.com/39720490/99200634-6fc80080-2774-11eb-95fe-5f015c1ea0ff.png)
In-game: 
![image](https://user-images.githubusercontent.com/39720490/99200642-79516880-2774-11eb-9591-f4eb7a4944dc.png)

**Comment by ayyaruq** [comment]
This is due to #15, the filter is incorrect. MP cost is hidden for all jobs, not just BLU, since the filter is hiding when the CostType isn't 0, even tho MP is 3.
